---
apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: chat-app
type: Opaque
data:
  jwt: YjM3NzY2NTI1Y2MxODJhM2NkYTJhYzBmOGRhM2VkM2M4YWVmMjdjMWVjMmZmMDExMmIyZmMyMjQwNGQ4MGY5Mg==

